version: '3.3'
services:
  db:
    image: postgis/postgis:12-3.1
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    expose:
      - "5432"
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.14
    restart: always
    environment:
      - ./.env
    ports:
      - "5051:5051"
    depends_on:
      - db
            
  web:
    build: .
    command: /script.sh
    restart: always
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./darcy:/usr/src/app
      - static_volume:/usr/src/app/staticfiles

  nginx:
    image: nginx:1.19.0-alpine
    expose:
      - "7080"
    ports:
      - "7080:7080"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - web
    restart: always
      
volumes:
  postgres-data:
  static_volume:
