version: '3'

volumes:
  darcydb_local_postgres_data: {}
  darcydb_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: darcydb_local_django
    restart: on-failure:3

    container_name: darcydb_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: darcydb_production_postgres
    restart: on-failure:3

    container_name: darcydb_local_postgres
    volumes:
      - darcydb_local_postgres_data:/var/lib/postgresql/data
      - darcydb_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  pgadmin:
    container_name: pgadmin4_local
    image: dpage/pgadmin4
    restart: on-failure:3

    expose:
      - '80'
    env_file:
      - ./.envs/.local/.pgadmin
    ports:
      - '5050:80'
    depends_on:
      - postgres

  docs:
    image: darcydb_local_docs
    container_name: darcydb_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    restart: on-failure:3

    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./darcydb:/app/darcydb:z
    ports:
      - '9000:9000'
    command: /start-docs

  redis:
    image: redis:6
    restart: on-failure:3

    container_name: darcydb_local_redis

  celeryworker:
    <<: *django
    image: darcydb_local_celeryworker
    container_name: darcydb_local_celeryworker
    restart: on-failure:3

    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: darcydb_local_celerybeat
    container_name: darcydb_local_celerybeat
    restart: on-failure:3

    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: darcydb_local_flower
    container_name: darcydb_local_flower
    restart: on-failure:3

    ports:
      - '5555:5555'
    command: /start-flower
