version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}
  production_pgadmin_data: {}
  production_webmin_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: darcydb_production_django
    volumes:
      - production_django_media:/app/darcydb/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: darcydb_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
      
  pgadmin:
    container_name: pgadmin4_local
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.envs/.production/.pgadmin
    volumes:
      - production_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
  
  geoserver:
    image: docker.osgeo.org/geoserver:2.24.x
    container_name: geoserver_local
    restart: always
    volumes:
      - ./geoserver/data_dir_25k/:/opt/geoserver_data/
      - ./geoserver/geo-web.xml:/opt/apache-tomcat-9.0.74/webapps/geoserver/WEB-INF/web.xml
      - ./geoserver/tomcat-web.xml:/apache-tomcat-9.0.74/conf/web.xml
    expose:
      - "8080"
  
  webmin:
    build:
      context: .
      dockerfile: ./compose/production/webmin/Dockerfile
    ports:
      - '10000:10000'
    env_file:
      - ./.envs/.production/.webmin
    volumes:
      - production_webmin_data:/etc/webmin

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: darcydb_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: darcydb_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: darcydb_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: darcydb_production_flower
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: darcydb_local_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
