# Generated by Django 4.1.9 on 2023-06-08 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("darcy_app", "0003_documents_authors_historicaldocuments_authors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documents",
            name="number_rgf",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Инвентарный номер Росгеолфонда",
            ),
        ),
        migrations.AddField(
            model_name="documents",
            name="number_tfgi",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Инвентарный номер ТФГИ",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocuments",
            name="number_rgf",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Инвентарный номер Росгеолфонда",
            ),
        ),
        migrations.AddField(
            model_name="historicaldocuments",
            name="number_tfgi",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Инвентарный номер ТФГИ",
            ),
        ),
        migrations.AlterField(
            model_name="documents",
            name="authors",
            field=models.TextField(
                blank=True,
                help_text="Перечислите авторов через запятую",
                null=True,
                verbose_name="Авторы",
            ),
        ),
        migrations.AlterField(
            model_name="documents",
            name="typo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="darcy_app.dictentities",
                verbose_name="Тип документа",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocuments",
            name="authors",
            field=models.TextField(
                blank=True,
                help_text="Перечислите авторов через запятую",
                null=True,
                verbose_name="Авторы",
            ),
        ),
        migrations.CreateModel(
            name="DictDocOrganizations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        default="ufo",
                        editable=False,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "remote_addr",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("extra", models.JSONField(blank=True, editable=False, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.TextField(verbose_name="Название организации")),
                (
                    "last_user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "db_table": "dict_doc_organization",
            },
        ),
        migrations.AlterField(
            model_name="documents",
            name="org_customer",
            field=models.ForeignKey(
                blank=True,
                db_column="org_customer",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="org_customer",
                to="darcy_app.dictdocorganizations",
                verbose_name="Организация-заказчик",
            ),
        ),
        migrations.AlterField(
            model_name="documents",
            name="org_executor",
            field=models.ForeignKey(
                blank=True,
                db_column="org_executor",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="org_executor",
                to="darcy_app.dictdocorganizations",
                verbose_name="Организация-исполнитель",
            ),
        ),
        migrations.AlterField(
            model_name="documents",
            name="source",
            field=models.ForeignKey(
                blank=True,
                db_column="source",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="doc_source",
                to="darcy_app.dictdocorganizations",
                verbose_name="Источник поступления",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocuments",
            name="org_customer",
            field=models.ForeignKey(
                blank=True,
                db_column="org_customer",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="darcy_app.dictdocorganizations",
                verbose_name="Организация-заказчик",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocuments",
            name="org_executor",
            field=models.ForeignKey(
                blank=True,
                db_column="org_executor",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="darcy_app.dictdocorganizations",
                verbose_name="Организация-исполнитель",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocuments",
            name="source",
            field=models.ForeignKey(
                blank=True,
                db_column="source",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="darcy_app.dictdocorganizations",
                verbose_name="Источник поступления",
            ),
        ),
    ]
