# Generated by Django 4.1.9 on 2023-06-20 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("darcy_app", "0004_documents_number_rgf_documents_number_tfgi_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wellsdepression",
            options={"verbose_name": "Журнал ОФР", "verbose_name_plural": "Журнал ОФР"},
        ),
        migrations.AlterUniqueTogether(
            name="wellsrate",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="wellswaterdepth",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="historicalwellsdepression",
            name="time_measure",
        ),
        migrations.AddField(
            model_name="historicalwellsrate",
            name="time_measure",
            field=models.TimeField(default="00:00:00.000", verbose_name="Время замера"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalwellswaterdepth",
            name="time_measure",
            field=models.TimeField(default="00:00:00.000", verbose_name="Время замера"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wellsrate",
            name="time_measure",
            field=models.TimeField(default="00:00:00.000", verbose_name="Время замера"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wellswaterdepth",
            name="time_measure",
            field=models.TimeField(default="00:00:00.000", verbose_name="Время замера"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dictdocorganizations",
            name="name",
            field=models.TextField(unique=True, verbose_name="Название организации"),
        ),
        migrations.AlterField(
            model_name="historicalwellsregime",
            name="date",
            field=models.DateField(verbose_name="Дата замера"),
        ),
        migrations.AlterField(
            model_name="wellsregime",
            name="date",
            field=models.DateField(verbose_name="Дата замера"),
        ),
        migrations.AlterUniqueTogether(
            name="wellsdepression",
            unique_together={("efw_id",)},
        ),
        migrations.AlterUniqueTogether(
            name="wellsrate",
            unique_together={("object_id", "content_type", "time_measure")},
        ),
        migrations.AlterUniqueTogether(
            name="wellswaterdepth",
            unique_together={("object_id", "content_type", "time_measure")},
        ),
        migrations.CreateModel(
            name="HistoricalWellsDrilledData",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        default="ufo",
                        editable=False,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "remote_addr",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("extra", models.JSONField(blank=True, editable=False, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("date", models.DateField(verbose_name="Дата бурения")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "doc",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="darcy_app.documents",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="darcy_app.wells",
                        verbose_name="Номер скважины",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Данные бурения",
                "verbose_name_plural": "historical Данные бурения",
                "db_table": "wells_drilled_data_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name="wellsdepression",
            name="time_measure",
        ),
        migrations.CreateModel(
            name="WellsDrilledData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        default="ufo",
                        editable=False,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "remote_addr",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("extra", models.JSONField(blank=True, editable=False, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("date", models.DateField(verbose_name="Дата бурения")),
                (
                    "doc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="darcy_app.documents",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "last_user",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="darcy_app.wells",
                        verbose_name="Номер скважины",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные бурения",
                "verbose_name_plural": "Данные бурения",
                "db_table": "wells_drilled_data",
                "ordering": ("-date", "well"),
                "unique_together": {("well", "date")},
            },
        ),
    ]
