# Generated by Django 4.1.10 on 2023-08-23 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("darcy_app", "0009_alter_wellslithology_caverns_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wellssample",
            unique_together={("well", "date", "name")},
        ),
    ]
