# Generated by Django 4.1.10 on 2023-08-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("darcy_app", "0011_license_alter_wellsdrilleddata_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictequipment",
            name="brand",
            field=models.CharField(max_length=50, verbose_name="Марка"),
        ),
        migrations.AlterField(
            model_name="dictequipment",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Название"
            ),
        ),
    ]
