# Generated by Django 4.1.10 on 2023-08-24 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("darcy_app", "0012_alter_dictequipment_brand_alter_dictequipment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wellsefw",
            name="pump_type",
            field=models.ForeignKey(
                blank=True,
                db_column="pump_type",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pump_type",
                to="darcy_app.dictequipment",
                verbose_name="Тип водоподъемного оборудования",
            ),
        ),
    ]
