# Generated by Django 4.1.10 on 2023-08-26 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("darcy_app", "0014_historicalwateruserschange_historicalwaterusers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalwellsdepression",
            old_name="efw_id",
            new_name="efw",
        ),
        migrations.RenameField(
            model_name="wellsdepression",
            old_name="efw_id",
            new_name="efw",
        ),
    ]
