# Generated by Django 4.1.10 on 2023-09-06 16:44

import darcydb.darcy_app.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("darcy_app", "0015_rename_efw_id_historicalwellsdepression_efw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwellsefw",
            name="rate_measure",
            field=models.ForeignKey(
                blank=True,
                db_column="rate_measure",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="darcy_app.dictequipment",
                verbose_name="Расходомер",
            ),
        ),
        migrations.AddField(
            model_name="wellsefw",
            name="rate_measure",
            field=models.ForeignKey(
                blank=True,
                db_column="rate_measure",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="rate_measure",
                to="darcy_app.dictequipment",
                verbose_name="Расходомер",
            ),
        ),
        migrations.AlterField(
            model_name="attachments",
            name="img",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/app/darcydb/media"
                ),
                upload_to="images/",
                verbose_name="Вложение",
            ),
        ),
        migrations.AlterField(
            model_name="documentspath",
            name="path",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/app/darcydb/media"
                ),
                upload_to=darcydb.darcy_app.models.user_directory_path,
                verbose_name="Файл документа",
            ),
        ),
    ]
