# Generated by Django 4.1.10 on 2023-09-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("darcy_app", "0016_historicalwellsefw_rate_measure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwellsefw",
            name="pump_time",
            field=models.DurationField(verbose_name="Продолжительность опыта"),
        ),
        migrations.AlterField(
            model_name="wellsefw",
            name="pump_time",
            field=models.DurationField(verbose_name="Продолжительность опыта"),
        ),
    ]
