# Generated by Django 4.1.10 on 2023-09-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("darcy_app", "0017_alter_historicalwellsefw_pump_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwellsrate",
            name="time_measure",
            field=models.DurationField(verbose_name="Время замера"),
        ),
        migrations.AlterField(
            model_name="historicalwellstemperature",
            name="time_measure",
            field=models.DurationField(verbose_name="Время замера"),
        ),
        migrations.AlterField(
            model_name="historicalwellswaterdepth",
            name="time_measure",
            field=models.DurationField(verbose_name="Время замера"),
        ),
        migrations.AlterField(
            model_name="wellsrate",
            name="time_measure",
            field=models.DurationField(verbose_name="Время замера"),
        ),
        migrations.AlterField(
            model_name="wellstemperature",
            name="time_measure",
            field=models.DurationField(verbose_name="Время замера"),
        ),
        migrations.AlterField(
            model_name="wellswaterdepth",
            name="time_measure",
            field=models.DurationField(verbose_name="Время замера"),
        ),
    ]
