# Generated by Django 4.1.10 on 2023-09-07 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("darcy_app", "0020_alter_documents_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documents",
            unique_together={("name", "typo")},
        ),
    ]
