# Generated by Django 4.1.10 on 2023-09-08 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("darcy_app", "0021_alter_documents_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dictequipment",
            unique_together={("brand", "typo")},
        ),
    ]
