# Generated by Django 4.1.10 on 2023-09-08 18:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("darcy_app", "0022_alter_dictequipment_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachments",
            name="img",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/app/darcydb/media"
                ),
                upload_to="images/",
                verbose_name="Вложение",
            ),
        ),
    ]
