# Generated by Django 4.1.10 on 2023-09-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("darcy_app", "0024_historicalwellsdrilleddata_drill_rig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="links",
            field=models.ManyToManyField(
                blank=True, to="darcy_app.documents", verbose_name="Связанные документы"
            ),
        ),
    ]
