# Generated by Django 4.1.12 on 2023-11-08 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("darcy_app", "0026_historicalwellslugheight_wellslugheight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aquifercodes",
            options={
                "verbose_name": "Гидрогеологическое подразделение",
                "verbose_name_plural": "►Справочник гидрогеологических подразделений",
            },
        ),
        migrations.AlterModelOptions(
            name="attachments",
            options={"verbose_name": "Вложение", "verbose_name_plural": "●Вложения"},
        ),
        migrations.AlterModelOptions(
            name="balance",
            options={"verbose_name": "Утвержденные запасы", "verbose_name_plural": "●Утвержденные запасы"},
        ),
        migrations.AlterModelOptions(
            name="chemcodes",
            options={
                "ordering": ("chem_name",),
                "verbose_name": "Показатель хим. состава",
                "verbose_name_plural": "►Справочник показателей хим.состава",
            },
        ),
        migrations.AlterModelOptions(
            name="dictdocorganizations",
            options={"verbose_name": "Организация", "verbose_name_plural": "►Справочник организаций"},
        ),
        migrations.AlterModelOptions(
            name="dictentities",
            options={"verbose_name": "Справочник сущностей", "verbose_name_plural": "►Справочник Типы сущностей"},
        ),
        migrations.AlterModelOptions(
            name="dictequipment",
            options={"verbose_name": "Справочник оборудования", "verbose_name_plural": "►Справочник обородувания"},
        ),
        migrations.AlterModelOptions(
            name="documents",
            options={"ordering": ("-creation_date",), "verbose_name": "Документ", "verbose_name_plural": "●Документы"},
        ),
        migrations.AlterModelOptions(
            name="entities",
            options={"verbose_name": "Сущность", "verbose_name_plural": "►Справочник Сущности"},
        ),
        migrations.AlterModelOptions(
            name="fields",
            options={
                "ordering": ("field_name",),
                "verbose_name": "Месторождение подземных вод",
                "verbose_name_plural": "►Справочник Месторождения подземных вод",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalattachments",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Вложение",
                "verbose_name_plural": "historical ●Вложения",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbalance",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Утвержденные запасы",
                "verbose_name_plural": "historical ●Утвержденные запасы",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldocuments",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Документ",
                "verbose_name_plural": "historical ●Документы",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalfields",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Месторождение подземных вод",
                "verbose_name_plural": "historical ►Справочник Месторождения подземных вод",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalintakes",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Водозабор",
                "verbose_name_plural": "historical ►Справочник Водозаборы",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallicense",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Лицензия",
                "verbose_name_plural": "historical ►Справочник Лицензии",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalwaterusers",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Водопользователь",
                "verbose_name_plural": "historical ►Справочник Водопользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalwellschem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Гидрогеохимия",
                "verbose_name_plural": "historical ●Гидрогеохимия",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalwellscondition",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Тех.состояние скважины",
                "verbose_name_plural": "historical ●Тех.состояние скважин",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalwellsdepth",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Глубина скважины",
                "verbose_name_plural": "historical ●Глубина скважин",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalwellslugheight",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Высота оголовка скважины",
                "verbose_name_plural": "historical ●Высоты оголовков скважин",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalwellsrate",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Замер дебита",
                "verbose_name_plural": "historical ●Замеры дебита",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalwellstemperature",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Замер температуры подземных вод",
                "verbose_name_plural": "historical ●Замеры температуры подземных вод",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalwellswaterdepth",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Замер уровня подземных вод",
                "verbose_name_plural": "historical ●Замеры уровня подземных вод",
            },
        ),
        migrations.AlterModelOptions(
            name="intakes",
            options={"verbose_name": "Водозабор", "verbose_name_plural": "►Справочник Водозаборы"},
        ),
        migrations.AlterModelOptions(
            name="license",
            options={"verbose_name": "Лицензия", "verbose_name_plural": "►Справочник Лицензии"},
        ),
        migrations.AlterModelOptions(
            name="waterusers",
            options={"verbose_name": "Водопользователь", "verbose_name_plural": "►Справочник Водопользователи"},
        ),
        migrations.AlterModelOptions(
            name="wellschem",
            options={
                "ordering": ("parameter__chem_name",),
                "verbose_name": "Гидрогеохимия",
                "verbose_name_plural": "●Гидрогеохимия",
            },
        ),
        migrations.AlterModelOptions(
            name="wellscondition",
            options={"verbose_name": "Тех.состояние скважины", "verbose_name_plural": "●Тех.состояние скважин"},
        ),
        migrations.AlterModelOptions(
            name="wellsdepth",
            options={"verbose_name": "Глубина скважины", "verbose_name_plural": "●Глубина скважин"},
        ),
        migrations.AlterModelOptions(
            name="wellslugheight",
            options={"verbose_name": "Высота оголовка скважины", "verbose_name_plural": "●Высоты оголовков скважин"},
        ),
        migrations.AlterModelOptions(
            name="wellsrate",
            options={"verbose_name": "Замер дебита", "verbose_name_plural": "●Замеры дебита"},
        ),
        migrations.AlterModelOptions(
            name="wellstemperature",
            options={
                "verbose_name": "Замер температуры подземных вод",
                "verbose_name_plural": "●Замеры температуры подземных вод",
            },
        ),
        migrations.AlterModelOptions(
            name="wellswaterdepth",
            options={
                "verbose_name": "Замер уровня подземных вод",
                "verbose_name_plural": "●Замеры уровня подземных вод",
            },
        ),
    ]
