# Generated by Django 4.1.12 on 2023-11-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("darcy_app", "0027_alter_aquifercodes_options_alter_attachments_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwellswaterdepth",
            name="time_measure",
            field=models.DurationField(blank=True, null=True, verbose_name="Время замера"),
        ),
        migrations.AlterField(
            model_name="wellswaterdepth",
            name="time_measure",
            field=models.DurationField(blank=True, null=True, verbose_name="Время замера"),
        ),
    ]
