# Generated by Django 4.0.7 on 2022-09-16 11:58

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gwm', '0003_alter_spr_entity_options_alter_spr_type_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalspr_type',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='тип', max_length=255, verbose_name='тип')),
                ('extra', models.JSONField(blank=True, help_text='неструктуированные данные', null=True, verbose_name='extra')),
                ('remote_addr', models.GenericIPAddressField(blank=True, editable=False, help_text='IP адрес последнего отредактировавшего (заполняется автоматически)', null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Дата-время создания (заполняется автоматически)', null=True, verbose_name='Создана')),
                ('modified', models.DateTimeField(blank=True, editable=False, help_text='Дата-время последнего редактирования (заполняется автоматически)', null=True, verbose_name='Отредактирована')),
                ('author', models.CharField(default='ufo', editable=False, help_text='Пользователь создавший запись (заполняется автоматически)', max_length=255, verbose_name='Кто создал')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Если вы не знаете что это - значит оно вам не надо', verbose_name='UUID')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('apply_to', models.ForeignKey(blank=True, db_constraint=False, help_text='выбрать сущность', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gwm.spr_entity', verbose_name='для')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lastuser', models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='Последний пользователь, редактировавший запись (заполняется автоматически)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Справочник Тип',
                'verbose_name_plural': 'historical Справочник Типы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalspr_entity',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='сущность', max_length=255, verbose_name='сущность')),
                ('extra', models.JSONField(blank=True, help_text='неструктуированные данные', null=True, verbose_name='extra')),
                ('remote_addr', models.GenericIPAddressField(blank=True, editable=False, help_text='IP адрес последнего отредактировавшего (заполняется автоматически)', null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Дата-время создания (заполняется автоматически)', null=True, verbose_name='Создана')),
                ('modified', models.DateTimeField(blank=True, editable=False, help_text='Дата-время последнего редактирования (заполняется автоматически)', null=True, verbose_name='Отредактирована')),
                ('author', models.CharField(default='ufo', editable=False, help_text='Пользователь создавший запись (заполняется автоматически)', max_length=255, verbose_name='Кто создал')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Если вы не знаете что это - значит оно вам не надо', verbose_name='UUID')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lastuser', models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='Последний пользователь, редактировавший запись (заполняется автоматически)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Справочник Сущность',
                'verbose_name_plural': 'historical Справочник `сущности`',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
