# Generated by Django 4.0.7 on 2022-09-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwm', '0004_historicalspr_type_historicalspr_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='foto', verbose_name='фото')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'фото',
            },
        ),
    ]
