# Generated by Django 4.0.7 on 2022-09-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwm', '0006_historicalobservation_foto_observation_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpoi',
            name='height',
            field=models.FloatField(blank=True, help_text='указать абсолютную отметку', null=True, verbose_name='абс.отм'),
        ),
        migrations.AddField(
            model_name='poi',
            name='height',
            field=models.FloatField(blank=True, help_text='указать абсолютную отметку', null=True, verbose_name='абс.отм'),
        ),
    ]
