# Generated by Django 4.0.7 on 2022-09-16 14:27

from django.db import migrations, models
import gwm.models


class Migration(migrations.Migration):

    dependencies = [
        ('gwm', '0007_historicalpoi_height_poi_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpoi',
            name='geom_error',
            field=models.FloatField(blank=True, null=True, validators=[gwm.models.validate_positive_float], verbose_name='погрешность замера координат, м'),
        ),
        migrations.AddField(
            model_name='poi',
            name='geom_error',
            field=models.FloatField(blank=True, null=True, validators=[gwm.models.validate_positive_float], verbose_name='погрешность замера координат, м'),
        ),
    ]
