# Generated by Django 4.0.7 on 2022-09-16 15:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwm', '0008_historicalpoi_geom_error_poi_geom_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpoi',
            name='typo',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gwm.spr_type', verbose_name='тип'),
        ),
        migrations.AddField(
            model_name='poi',
            name='typo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gwm.spr_type', verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='historicalpoi',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='указать точку, например: SRID=4326;POINT(37.573866731132966 55.78122028929206 120)', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='historicalpoi',
            name='nom',
            field=models.CharField(db_index=True, help_text='указать номер скважины', max_length=255, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='указать точку, например: SRID=4326;POINT(37.573866731132966 55.78122028929206 120)', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='poi',
            name='nom',
            field=models.CharField(help_text='указать номер скважины', max_length=255, unique=True, verbose_name='номер'),
        ),
    ]
