# Generated by Django 4.0.7 on 2022-09-16 19:01

from django.db import migrations, models
import gwm.models


class Migration(migrations.Migration):

    dependencies = [
        ('gwm', '0010_remove_historicalobservation_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobservation',
            name='passport',
            field=models.TextField(blank=True, help_text='Ссылка на PDF с паспортом, если есть', max_length=100, null=True, validators=[gwm.models.validate_file_extension_pdf], verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='observation',
            name='passport',
            field=models.FileField(blank=True, help_text='Ссылка на PDF с паспортом, если есть', null=True, upload_to='passport', validators=[gwm.models.validate_file_extension_pdf], verbose_name='PDF'),
        ),
    ]
