# Generated by Django 4.0.7 on 2022-09-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwm', '0011_historicalobservation_passport_observation_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalobservation',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='foto',
        ),
    ]
