# Generated by Django 4.0.7 on 2022-09-17 11:06

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gwm', '0012_remove_historicalobservation_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='author',
            field=models.CharField(default='ufo', editable=False, help_text='Пользователь создавший запись (заполняется автоматически)', max_length=255, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='foto',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, help_text='Дата-время создания (заполняется автоматически)', null=True, verbose_name='Создана'),
        ),
        migrations.AddField(
            model_name='foto',
            name='lastuser',
            field=models.ForeignKey(blank=True, editable=False, help_text='Последний пользователь, редактировавший запись (заполняется автоматически)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foto',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, help_text='Дата-время последнего редактирования (заполняется автоматически)', null=True, verbose_name='Отредактирована'),
        ),
        migrations.AddField(
            model_name='foto',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gwm.observation'),
        ),
        migrations.AddField(
            model_name='foto',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, editable=False, help_text='IP адрес последнего отредактировавшего (заполняется автоматически)', null=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Если вы не знаете что это - значит оно вам не надо', verbose_name='UUID'),
        ),
    ]
