# Generated by Django 4.0.7 on 2022-09-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwm', '0013_foto_author_foto_created_foto_lastuser_foto_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalspr_datasource',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Справочник Источник данных', 'verbose_name_plural': 'historical •Справочник Источник данных'},
        ),
        migrations.AlterModelOptions(
            name='historicalspr_entity',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Справочник Сущность', 'verbose_name_plural': 'historical •Справочник `сущности`'},
        ),
        migrations.AlterModelOptions(
            name='historicalspr_type',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Справочник Тип', 'verbose_name_plural': 'historical •Справочник Типы'},
        ),
        migrations.AlterModelOptions(
            name='historicalspr_vzu',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Справочник Водозабор', 'verbose_name_plural': 'historical •Справочник Водозаборы'},
        ),
        migrations.AlterModelOptions(
            name='spr_datasource',
            options={'verbose_name': 'Справочник Источник данных', 'verbose_name_plural': '•Справочник Источник данных'},
        ),
        migrations.AlterModelOptions(
            name='spr_entity',
            options={'verbose_name': 'Справочник Сущность', 'verbose_name_plural': '•Справочник `сущности`'},
        ),
        migrations.AlterModelOptions(
            name='spr_type',
            options={'verbose_name': 'Справочник Тип', 'verbose_name_plural': '•Справочник Типы'},
        ),
        migrations.AlterModelOptions(
            name='spr_vzu',
            options={'verbose_name': 'Справочник Водозабор', 'verbose_name_plural': '•Справочник Водозаборы'},
        ),
        migrations.AddField(
            model_name='historicalobservation',
            name='date_end',
            field=models.DateField(blank=True, help_text='введите дату обследования', null=True, verbose_name='Дата обследования'),
        ),
        migrations.AddField(
            model_name='observation',
            name='date_end',
            field=models.DateField(blank=True, help_text='введите дату обследования', null=True, verbose_name='Дата обследования'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='description',
            field=models.CharField(blank=True, help_text='ввести краткое (255 символов) описание фотографии', max_length=255, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='observation',
            field=models.ForeignKey(blank=True, help_text='выбрать Обследование', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwm.observation', verbose_name='обследование'),
        ),
    ]
