# Generated by Django 4.0.7 on 2022-09-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwm', '0014_alter_historicalspr_datasource_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalobservation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Обследование', 'verbose_name_plural': 'historical обследования [скважин]'},
        ),
        migrations.AlterModelOptions(
            name='historicalspr_entity',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Справочник Сущность', 'verbose_name_plural': 'historical •Справочник `сущности к типам`'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'verbose_name': 'Обследование', 'verbose_name_plural': 'обследования [скважин]'},
        ),
        migrations.AlterModelOptions(
            name='spr_entity',
            options={'verbose_name': 'Справочник Сущность', 'verbose_name_plural': '•Справочник `сущности к типам`'},
        ),
        migrations.AddField(
            model_name='historicalpoi',
            name='vzu',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gwm.spr_vzu', verbose_name='ВЗУ'),
        ),
        migrations.AddField(
            model_name='poi',
            name='vzu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gwm.spr_vzu', verbose_name='ВЗУ'),
        ),
    ]
