# Generated by Django 4.0.7 on 2022-09-19 14:36

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import gwm.models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gwm', '0015_alter_historicalobservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobservation',
            name='depth',
            field=models.FloatField(blank=True, help_text='указать глубину скважины по результатам обследования', null=True, validators=[gwm.models.validate_positive_float], verbose_name='глубина, м'),
        ),
        migrations.AddField(
            model_name='historicalobservation',
            name='height_cap',
            field=models.FloatField(blank=True, help_text='указать высоту оголовка от поверхности земли по результатам обследования', null=True, validators=[gwm.models.validate_positive_float], verbose_name='оголовок, см'),
        ),
        migrations.AddField(
            model_name='historicalobservation',
            name='pump_depth',
            field=models.FloatField(blank=True, help_text='указать глубину загрузки насоса по результатам обследования', null=True, validators=[gwm.models.validate_positive_float], verbose_name='загрузка, м'),
        ),
        migrations.AddField(
            model_name='historicalobservation',
            name='state',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='выбрать состояние скважины', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gwm.spr_type', verbose_name='состояние'),
        ),
        migrations.AddField(
            model_name='observation',
            name='depth',
            field=models.FloatField(blank=True, help_text='указать глубину скважины по результатам обследования', null=True, validators=[gwm.models.validate_positive_float], verbose_name='глубина, м'),
        ),
        migrations.AddField(
            model_name='observation',
            name='height_cap',
            field=models.FloatField(blank=True, help_text='указать высоту оголовка от поверхности земли по результатам обследования', null=True, validators=[gwm.models.validate_positive_float], verbose_name='оголовок, см'),
        ),
        migrations.AddField(
            model_name='observation',
            name='pump_depth',
            field=models.FloatField(blank=True, help_text='указать глубину загрузки насоса по результатам обследования', null=True, validators=[gwm.models.validate_positive_float], verbose_name='загрузка, м'),
        ),
        migrations.AddField(
            model_name='observation',
            name='state',
            field=models.ForeignKey(blank=True, help_text='выбрать состояние скважины', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation_poi_state', to='gwm.spr_type', verbose_name='состояние'),
        ),
        migrations.CreateModel(
            name='spr_pumps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='насос', max_length=255, verbose_name='насос')),
                ('extra', models.JSONField(blank=True, help_text='неструктуированные данные', null=True, verbose_name='extra')),
                ('remote_addr', models.GenericIPAddressField(blank=True, editable=False, help_text='IP адрес последнего отредактировавшего (заполняется автоматически)', null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Дата-время создания (заполняется автоматически)', null=True, verbose_name='Создана')),
                ('modified', models.DateTimeField(blank=True, editable=False, help_text='Дата-время последнего редактирования (заполняется автоматически)', null=True, verbose_name='Отредактирована')),
                ('author', models.CharField(default='ufo', editable=False, help_text='Пользователь создавший запись (заполняется автоматически)', max_length=255, verbose_name='Кто создал')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Если вы не знаете что это - значит оно вам не надо', verbose_name='UUID')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('lastuser', models.ForeignKey(blank=True, editable=False, help_text='Последний пользователь, редактировавший запись (заполняется автоматически)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Справочник Марка насоса',
                'verbose_name_plural': '•Справочник Марки насосов',
            },
        ),
        migrations.CreateModel(
            name='Historicalspr_pumps',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='насос', max_length=255, verbose_name='насос')),
                ('extra', models.JSONField(blank=True, help_text='неструктуированные данные', null=True, verbose_name='extra')),
                ('remote_addr', models.GenericIPAddressField(blank=True, editable=False, help_text='IP адрес последнего отредактировавшего (заполняется автоматически)', null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Дата-время создания (заполняется автоматически)', null=True, verbose_name='Создана')),
                ('modified', models.DateTimeField(blank=True, editable=False, help_text='Дата-время последнего редактирования (заполняется автоматически)', null=True, verbose_name='Отредактирована')),
                ('author', models.CharField(default='ufo', editable=False, help_text='Пользователь создавший запись (заполняется автоматически)', max_length=255, verbose_name='Кто создал')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Если вы не знаете что это - значит оно вам не надо', verbose_name='UUID')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lastuser', models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='Последний пользователь, редактировавший запись (заполняется автоматически)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Справочник Марка насоса',
                'verbose_name_plural': 'historical •Справочник Марки насосов',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalobservation',
            name='pump',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='выбрать марку насоса', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gwm.spr_pumps', verbose_name='марка насоса'),
        ),
        migrations.AddField(
            model_name='observation',
            name='pump',
            field=models.ForeignKey(blank=True, help_text='выбрать марку насоса', null=True, on_delete=django.db.models.deletion.CASCADE, to='gwm.spr_pumps', verbose_name='марка насоса'),
        ),
    ]
