# Generated by Django 4.0.7 on 2022-09-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwm', '0016_historicalobservation_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpoi',
            name='gvk',
            field=models.CharField(blank=True, help_text='указать номер по Государственному водному кадастру', max_length=255, null=True, verbose_name='номер ГВК'),
        ),
        migrations.AddField(
            model_name='poi',
            name='gvk',
            field=models.CharField(blank=True, help_text='указать номер по Государственному водному кадастру', max_length=255, null=True, verbose_name='номер ГВК'),
        ),
    ]
