# Generated by Django 4.0.7 on 2022-09-24 18:37

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import gwm.models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gwm', '0017_historicalpoi_gvk_poi_gvk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobservation',
            name='econ_dppog',
            field=models.BooleanField(blank=True, default=False, help_text='указать есть ли Дополнение к предложению заявителя?', verbose_name='дополнение к предложению?'),
        ),
        migrations.AlterField(
            model_name='historicalobservation',
            name='econ_osv',
            field=models.BooleanField(blank=True, default=False, help_text='указать есть ли Оборотно-сальдовая ведомость (Выписка БУ)?', verbose_name='оборотно-сальдовая ведомость?'),
        ),
        migrations.AlterField(
            model_name='historicalobservation',
            name='econ_ppog',
            field=models.BooleanField(blank=True, default=False, help_text='указать есть ли Перечень тех средств?', verbose_name='предложения по обоснованию границ?'),
        ),
        migrations.AlterField(
            model_name='historicalobservation',
            name='econ_pts',
            field=models.BooleanField(blank=True, default=False, help_text='указать есть ли Перечень тех средств?', verbose_name='перечень тех.средств?'),
        ),
        migrations.AlterField(
            model_name='historicalobservation',
            name='econ_vbu',
            field=models.BooleanField(blank=True, default=False, help_text='указать есть ли Выписка БУ?', verbose_name='выписка БУ?'),
        ),
        migrations.AlterField(
            model_name='historicalobservation',
            name='econ_ztopo',
            field=models.BooleanField(blank=True, default=False, help_text='указать есть ли Пояснительная записка к топоплану?', verbose_name='записка к топоплану?'),
        ),
        migrations.AlterField(
            model_name='historicalpoi',
            name='geom_error',
            field=models.FloatField(blank=True, help_text='указать погрешность замера координат', null=True, validators=[gwm.models.validate_positive_float], verbose_name='погрешность, м'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='econ_dppog',
            field=models.BooleanField(blank=True, default=False, help_text='указать есть ли Дополнение к предложению заявителя?', verbose_name='дополнение к предложению?'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='econ_osv',
            field=models.BooleanField(blank=True, default=False, help_text='указать есть ли Оборотно-сальдовая ведомость (Выписка БУ)?', verbose_name='оборотно-сальдовая ведомость?'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='econ_ppog',
            field=models.BooleanField(blank=True, default=False, help_text='указать есть ли Перечень тех средств?', verbose_name='предложения по обоснованию границ?'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='econ_pts',
            field=models.BooleanField(blank=True, default=False, help_text='указать есть ли Перечень тех средств?', verbose_name='перечень тех.средств?'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='econ_vbu',
            field=models.BooleanField(blank=True, default=False, help_text='указать есть ли Выписка БУ?', verbose_name='выписка БУ?'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='econ_ztopo',
            field=models.BooleanField(blank=True, default=False, help_text='указать есть ли Пояснительная записка к топоплану?', verbose_name='записка к топоплану?'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='geom_error',
            field=models.FloatField(blank=True, help_text='указать погрешность замера координат', null=True, validators=[gwm.models.validate_positive_float], verbose_name='погрешность, м'),
        ),
        migrations.CreateModel(
            name='spr_change_reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите новую причину изменения строки', max_length=255, verbose_name='причина')),
                ('extra', models.JSONField(blank=True, help_text='неструктуированные данные', null=True, verbose_name='extra')),
                ('remote_addr', models.GenericIPAddressField(blank=True, editable=False, help_text='IP адрес последнего отредактировавшего (заполняется автоматически)', null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Дата-время создания (заполняется автоматически)', null=True, verbose_name='Создана')),
                ('modified', models.DateTimeField(blank=True, editable=False, help_text='Дата-время последнего редактирования (заполняется автоматически)', null=True, verbose_name='Отредактирована')),
                ('author', models.CharField(default='ufo', editable=False, help_text='Пользователь создавший запись (заполняется автоматически)', max_length=255, verbose_name='Кто создал')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Если вы не знаете что это - значит оно вам не надо', verbose_name='UUID')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('lastuser', models.ForeignKey(blank=True, editable=False, help_text='Последний пользователь, редактировавший запись (заполняется автоматически)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Справочник Причина изменений',
                'verbose_name_plural': '•Справочник Причины изменений',
            },
        ),
        migrations.CreateModel(
            name='Historicalspr_change_reason',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='введите новую причину изменения строки', max_length=255, verbose_name='причина')),
                ('extra', models.JSONField(blank=True, help_text='неструктуированные данные', null=True, verbose_name='extra')),
                ('remote_addr', models.GenericIPAddressField(blank=True, editable=False, help_text='IP адрес последнего отредактировавшего (заполняется автоматически)', null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Дата-время создания (заполняется автоматически)', null=True, verbose_name='Создана')),
                ('modified', models.DateTimeField(blank=True, editable=False, help_text='Дата-время последнего редактирования (заполняется автоматически)', null=True, verbose_name='Отредактирована')),
                ('author', models.CharField(default='ufo', editable=False, help_text='Пользователь создавший запись (заполняется автоматически)', max_length=255, verbose_name='Кто создал')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Если вы не знаете что это - значит оно вам не надо', verbose_name='UUID')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lastuser', models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='Последний пользователь, редактировавший запись (заполняется автоматически)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Справочник Причина изменений',
                'verbose_name_plural': 'historical •Справочник Причины изменений',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
