# Generated by Django 4.0.7 on 2023-04-10 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gwm', '0018_alter_historicalobservation_econ_dppog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='foto', verbose_name='фото')),
                ('description', models.CharField(blank=True, help_text='ввести краткое (255 символов) описание фотографии', max_length=255, null=True, verbose_name='описание')),
                ('object_id', models.PositiveIntegerField()),
                ('remote_addr', models.GenericIPAddressField(blank=True, editable=False, help_text='IP адрес последнего отредактировавшего (заполняется автоматически)', null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Дата-время создания (заполняется автоматически)', null=True, verbose_name='Создана')),
                ('modified', models.DateTimeField(blank=True, editable=False, help_text='Дата-время последнего редактирования (заполняется автоматически)', null=True, verbose_name='Отредактирована')),
                ('author', models.CharField(default='ufo', editable=False, help_text='Пользователь создавший запись (заполняется автоматически)', max_length=255, verbose_name='Кто создал')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Если вы не знаете что это - значит оно вам не надо', verbose_name='UUID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('lastuser', models.ForeignKey(blank=True, editable=False, help_text='Последний пользователь, редактировавший запись (заполняется автоматически)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'фото',
            },
        ),
    ]
