name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # создание хранилища для ssh. На гитхабе лежит приватный, на сервере публичный
    # приватный записывается в файл в среде github_actions, устанавливаются разрешения на чтение
    # затем этот файл используется для авторизации на сервере по ssh
    - name: Setup SSH
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 600 ssh_key
        mkdir -p ~/.ssh
        ssh-keyscan 84.201.157.155 >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    # пул репозитория на сервер
    - name: Deploy to Server
      run: |
        ssh -i ./ssh_key actions@84.201.157.155 "cd .. && cd master/groundwater/ && git pull origin master"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    # сборка образа
    - name: Build and run Docker Compose
      run: |
        ssh -i ./ssh_key actions@84.201.157.155 "cd .. && cd master/groundwater/ && docker compose -f local.yml up -d --build"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    # удаление кэша и старых образов
    - name: Remove Unused Docker Containers and Images
      run: |
        ssh -i ./ssh_key actions@84.201.157.155 "docker system prune --all --force"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
